noClasses = false
version = 3
baseURL = "http://192.168.40.13:1313"
defaultContentLanguage = "en"
languageCode = "en"
title = "Per-Tech"
description = "Azure architecture insights, automation tutorials, and homelab experiments from a passionate cloud architect"
theme = "DoIt"

[params]
  version = "0.4.X"
  # Date format for posts (without "published on" prefix)
  dateformat = "January 2, 2006"
  # Image processing configuration
  [params.image]
    # Enable image optimization
    optimise = true
    # Cache remote images for better performance
    cacheRemote = true

[params.page.toc]
  # whether to enable the table of the contents
  enable = true
  # DoIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
  keepStatic = false
  # whether to make the table of the contents in the sidebar automatically collapsed
  auto = false

[[menu.main]]
  identifier = "home"
  pre = ""
  post = ""
  name = "Home"
  url = "/"
  title = ""
  weight = 5

[[menu.main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "About"
  url = "/about/"
  title = ""
  weight = 10

[[menu.main]]
  identifier = "posts"
  pre = ""
  post = ""
  name = "Posts"
  url = "/posts/"
  title = ""
  weight = 20

[[menu.main]]
  identifier = "tags"
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""
  weight = 30

[[menu.main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "Categories"
  url = "/categories/"
  title = ""
  weight = 40

# Footer config
[params.footer]
  enable = true
  # DoIt NEW | 0.2.0 Custom content (HTML format is supported)
  custom = '© 2025 Per-Tech. Some rights reserved.'
  # DoIt NEW | 0.2.0 whether to show Hugo and theme info
  hugo = false
  # DoIt NEW | 0.2.14 Hosted on (HTML format is supported)
  # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreferrer">GitHub Pages</a>
  hostedOn = ''
  # DoIt NEW | 0.2.0 whether to show copyright info
  copyright = false
  # DoIt NEW | 0.2.0 whether to show the author
  author = true
  # Site creation time
  since = 2025
  # ICP info only in China (HTML format is supported)
  icp = ""
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.home]
# DoIt NEW | 0.2.0 amount of RSS pages
  rss = 10
  # Home page profile
  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    # Place your avatar file under static or assets directory
    # The filepath is relative to the static or assets directory
    avatarURL = "/img/icons/persell.png"
    # URL the avatar links to
    avatarLinkURL = ""
    # DoIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    title = "Azure Architect & Automation Enthusiast"
    # subtitle shown in home page
    subtitle = "Architect, engineer, solutions builder"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # DoIt NEW | 0.2.0 disclaimer (HTML format is supported)
    # disclaimer = "Sharing insights on Azure, automation, and homelab adventures | All Rights Reserved Persell Machuca"
  # Home page posts
  [params.home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
    # DoIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
    # default behavior when you don't set "hiddenFromHomePage" in front matter
    defaultHiddenFromHomePage = false

[params.social]
  GitHub = "permach-tech"
  Linkedin = "persell-machuca"

[params.page]
  enableWordCount = false
  enableReadingTime = true
  enableLastMod = false
  # Enable cover image on post pages
  showImage = true
  # Custom CSS library config
  [params.page.library]
    [params.page.library.css]
      custom = "css/_override.scss"

[params.page.code]
  # the maximum number of lines of displayed code by default
  maxShownLines = 10
  # whether to enable line numbers in the code block
  lineNos = true
  # whether to enable line wrapping in the code block
  wrap = false
  # whether to display the header in the code block
  header = true

[outputformats.DNBINDEX]
  baseName = "dnbindex"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params.search]
  enable = true
  # type of search engine ("algolia", "fuse")
  type = "fuse"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  #  max number of results length
  maxResultLength = 10
  #  snippet length of the result
  snippetLength = 30
  #  HTML tag name of the highlight part in results
  highlightTag = "em"
  #  whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  [params.search.fuse]
    #  https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 5
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true